### PR TITLE
Implement the RDFJS Data Model spec.

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Partly implements issue #137.

- Implement DefaultGraph
- Implement literal.hasLanguage() as a serialization helper
- Store original Variable name in .value
- Literal - only serialize datatype if non-default
- Use duck typing to check for Node instance
- Update termType usage to match RDFJS interface

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Corresponding downstream PRs (to change the `termType` values):

* https://github.com/linkeddata/solid-ui/pull/2
* https://github.com/linkeddata/solid-app-set/pull/3
* https://github.com/linkeddata/tabulator/pull/13

**Comment by nicola** [comment]
AWESOME

**Comment by dmitrizagidulin** [comment]
@timbl Ready for review.

**Comment by dmitrizagidulin** [comment]
@timbl any other corrections to this PR, or can we merge it?

**Pull request merged**
