### PR TITLE
Updated addLiteral to properly support XMLLiteral

### PR DESCRIPTION
**Pull request by jamsden**
Parsing an XMLLiteral should store a normalized (sorted attributes) XML
string as the value for the literal, not the parsed XML dom.

Addresses issue #75.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@jamsden @timbl - is this PR ready to merge?

**Comment by jamsden** [comment]
It doesn’t do the attribution normalization (sorting the attributes) so === works on XMLLiterals that are the same except for ordering, but it does at least capture the correct contents.

Not sure === on XMLLiterals is a high priority, so this can possibly be deferred.

**Comment by timbl** [comment]
Sounds like a definite improvement - suggest merge

**Comment by timbl** [comment]
(I had earlier left the DOM pointer as th value, as that is what is useful to software. - if we have the DOM then maybe it would be be usefulk to leave a pointer to it, so that the caller doesn't have to waste time parsing it again?

**Comment by jamsden** [comment]
Good point, but it doesn't follow the RDF/XLM spec and creates inconsistencies for consumers. For example, it breaks OSLC resources.

**Comment by timbl** [comment]
This now needs to be patched in
 rdfxmlparser.js
at line: 
if (this.parent.datatype) {
Line 156 in rdfxmlparser.js

**Pull request closed without merging**
